export const data = [
  {
    title: "Descubre Bangkok",
    description: "Marruecos, África",
    image: "/img/placeholder1.png",
    price: 248.0,
    priceBase: 1124.0,
    taxes: 150.0,
    total: 2455.0,
    activity: "quads",
    destination: "madrid",
    accommodation: "hotel",
    numberOfdays: 9,
  },
  {
    title: "Aventura en el cielo",
    description: "Colombia",
    image: "/img/placeholder2.png",
    price: 199.0,
    priceBase: 980.0,
    taxes: 120.0,
    total: 2100.0,
    activity: "parapente",
    destination: "barcelona",
    accommodation: "department",
    numberOfdays: 5,
  },
  {
    title: "Surfea en Bali",
    description: "Indonesia",
    image: "/img/placeholder3.png",
    price: 270.0,
    priceBase: 1100.0,
    taxes: 160.0,
    total: 2390.0,
    activity: "surf",
    destination: "asia",
    accommodation: "house",
    numberOfdays: 6,
  },
  {
    title: "Descubre Bangkok",
    description: "Marruecos, África",
    image: "/img/placeholder1.png",
    price: 248.0,
    priceBase: 1124.0,
    taxes: 150.0,
    total: 2455.0,
    activity: "quads",
    destination: "asia",
    accommodation: "house",
    numberOfdays: 9,
  },
  {
    title: "Aventura en el cielo",
    description: "Colombia",
    image: "/img/placeholder2.png",
    price: 199.0,
    priceBase: 980.0,
    taxes: 120.0,
    total: 2100.0,
    activity: "parapente",
    destination: "america",
    accommodation: "department",
    numberOfdays: 5,
  },
  {
    title: "Surfea en Bali",
    description: "Indonesia",
    image: "/img/placeholder3.png",
    price: 270.0,
    priceBase: 1100.0,
    taxes: 160.0,
    total: 2390.0,
    activity: "surf",
    destination: "africa",
    accommodation: "hotel",
    numberOfdays: 6,
  },
  {
    title: "Surfea en Bali",
    description: "Indonesia",
    image: "/img/placeholder3.png",
    price: 270.0,
    priceBase: 1100.0,
    taxes: 160.0,
    total: 2390.0,
    activity: "surf",
    destination: "africa",
    accommodation: "hotel",
    numberOfdays: 6,
  },
  {
    title: "Surfea en Bali",
    description: "Indonesia",
    image: "/img/placeholder3.png",
    price: 270.0,
    priceBase: 1100.0,
    taxes: 160.0,
    total: 2390.0,
    activity: "surf",
    destination: "africa",
    accommodation: "hotel",
    numberOfdays: 6,
  },
  {
    title: "Surfea en Bali",
    description: "Indonesia",
    image: "/img/placeholder3.png",
    price: 270.0,
    priceBase: 1100.0,
    taxes: 160.0,
    total: 2390.0,
    activity: "surf",
    destination: "africa",
    accommodation: "hotel",
    numberOfdays: 6,
  },
];
